print ("welcome to the Band Name Generator")
city = input("which city did you grow up in? ")
print(city)
pet = input("whhat is the name of a pet?")
print("your band name could be: " + city + " " + pet)